### ISSUE TITLE
Does not work with Java 1.7

### ISSUE THREAD

**Issue by grifmeister** [versly/wsdoc#19]
Throws error on Maven build running AnnotationProcessor same config works with Java 1.6:

[INFO] diagnostic C:\Users\me\dev\workspaces\TNT\mytestapplication-service\src\main\generated\java\com\me\mytestapplication\resource\CustomerServiceResource.java:53: error: cannot find symbol
                    consumes = {MediaType.APPLICATION_XML_VALUE, MediaType.APPLICATION_JSON_VALUE}, 
                    ^
  symbol:   method consumes()
  location: @interface org.springframework.web.bind.annotation.RequestMapping

Method definition:

```
@RequestMapping(value = "/getcustomer/{id}", method = {RequestMethod.GET}, 
                consumes = {MediaType.APPLICATION_XML_VALUE, MediaType.APPLICATION_JSON_VALUE}, 
                produces = {MediaType.APPLICATION_XML_VALUE, MediaType.APPLICATION_JSON_VALUE})
@ResponseStatus(HttpStatus.OK)
@ResponseBody
public com.me.mytestapplication.service.wrapper.customerservice.GetCustomerResponse getCustomer(@PathVariable("id") Integer id) throws BusinessException, ServiceException {
```
